set(CUDA_TOOLKIT_ROOT_DIR /usr/local/cuda)
set(CUDA_LIBRARY_DIR ${CUDA_TOOLKIT_ROOT_DIR}/lib64)
set(CUDA_LIBRARY_STUBS_DIR ${CUDA_TOOLKIT_ROOT_DIR}/lib64/stubs)
set(RAPIDSAI_ROOT_DIR /usr/local/rapidsai)

find_library (CUDA_LIBRARY cuda PATHS ${CUDA_LIBRARY_STUBS_DIR})
find_library (CUDA_RT_LIBRARY cudart PATHS ${CUDA_LIBRARY_DIR})
find_library (RMM_LIBRARY rmm PATHS ${RAPIDSAI_ROOT_DIR}/lib)
find_library (CUDF_LIBRARY cudf PATHS ${RAPIDSAI_ROOT_DIR}/lib)
find_library (NVCATEGORY_LIBRARY NVCategory PATHS ${RAPIDSAI_ROOT_DIR}/lib)
find_library (NVSTRINGS_LIBRARY NVStrings PATHS ${RAPIDSAI_ROOT_DIR}/lib)
find_library (NVTEXT_LIBRARY NVText PATHS ${RAPIDSAI_ROOT_DIR}/lib)

find_path (CUDA_INCLUDE_DIR NAMES cuda.h PATHS ${CUDA_TOOLKIT_ROOT_DIR}/include)
find_path (CUDF_INCLUDE_DIR NAMES cudf/cudf.h PATHS ${RAPIDSAI_ROOT_DIR}/include)
find_path (CUDF_LIBCUDACXX_INCLUDE_DIR NAMES simt/chrono PATHS ${RAPIDSAI_ROOT_DIR}/libcudacxx/include)
find_path (CUDF_CUB_INCLUDE_DIR NAMES cub/cub.cuh PATHS ${RAPIDSAI_ROOT_DIR}/cub)
find_path (CUDF_JITIFY_INCLUDE_DIR NAMES jitify.hpp PATHS ${RAPIDSAI_ROOT_DIR}/jitify)

message (STATUS "Using cuda ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES} : ${CUDA_INCLUDE_DIR} : ${CUDA_LIBRARY} : ${CUDA_RT_LIBRARY}")
message (STATUS "Using rmm ${RMM_LIBRARY}")
message (STATUS "Using cudf ${CUDF_INCLUDE_DIR} : ${CUDF_LIBRARY}")
message (STATUS "Using cudf-libcudacxx ${CUDF_LIBCUDACXX_INCLUDE_DIR}")
message (STATUS "Using cudf-cub ${CUDF_CUB_INCLUDE_DIR}")
message (STATUS "Using cudf-jitify ${CUDF_JITIFY_INCLUDE_DIR}")
message (STATUS "Using NVCategory ${NVCATEGORY_LIBRARY}")
message (STATUS "Using NVStrings ${NVSTRINGS_LIBRARY}")
message (STATUS "Using NVText ${NVTEXT_LIBRARY}")
